// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ-ecr5X0-cJXcOmB_NNpP0wGyq7uT47k',
    appId: '1:968125070497:web:9c059db25b14b1cbd2c4e0',
    messagingSenderId: '968125070497',
    projectId: 'temelden-ffcb3',
    authDomain: 'temelden-ffcb3.firebaseapp.com',
    databaseURL:
        'https://temelden-ffcb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temelden-ffcb3.appspot.com',
    measurementId: 'G-FT50RD6Q5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZG8FBX-O3-rgfxxIiQEShw_IbJ7ZkUg',
    appId: '1:968125070497:android:edb5b2a6c1886a24d2c4e0',
    messagingSenderId: '968125070497',
    projectId: 'temelden-ffcb3',
    databaseURL:
        'https://temelden-ffcb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temelden-ffcb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9XHkT6tHGyu1onyfGnJbvRfg4XDk2VeU',
    appId: '1:968125070497:ios:111f31d9e2e46ec1d2c4e0',
    messagingSenderId: '968125070497',
    projectId: 'temelden-ffcb3',
    databaseURL:
        'https://temelden-ffcb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temelden-ffcb3.appspot.com',
    iosClientId:
        '968125070497-bmm7rjbhqr0keh66sispd1k608ea6d73.apps.googleusercontent.com',
    iosBundleId: 'com.example.temelden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9XHkT6tHGyu1onyfGnJbvRfg4XDk2VeU',
    appId: '1:968125070497:ios:111f31d9e2e46ec1d2c4e0',
    messagingSenderId: '968125070497',
    projectId: 'temelden-ffcb3',
    databaseURL:
        'https://temelden-ffcb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temelden-ffcb3.appspot.com',
    iosClientId:
        '968125070497-bmm7rjbhqr0keh66sispd1k608ea6d73.apps.googleusercontent.com',
    iosBundleId: 'com.example.temelden',
  );
}
